apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "cti-rss-teams-bot.fullname" . }}-secret
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
  {{- range $secret, $value := .Values.secrets }}
    {{ $secret }}: {{ $value }}
  {{- end }}